import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBarForMeny from "@/Components/NavBarForMeny";
import Footer from "@/Components/Footer";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="sv">
      <body className={inter.className}>
        <header className="flex items-center pt-10 pb-10 bg-gray-900 text-white">
          <h1 className="text-2xl ml-10 font-bold">The Quarter Men</h1>
          <div className="hidden sm:block sm:mr-auto sm:ml-auto">
            <NavBarForMeny />
          </div>

          <button className="block mr-auto ml-auto sm:hidden ">
            <Link href={"/NavigationMobile"}>Klick</Link>
          </button>
        </header>
        {children}
        <div className="hidden sm:block">
          <Footer />
        </div>
      </body>
    </html>
  );
}
